import { Injectable } from '@nestjs/common';
import { CreateTicketDto } from './dto/create-ticket.dto';
import { PrismaService } from 'src/prisma/prisma.service';
import { TicketStatus } from '@prisma/client'; // Assuming you have enums generated by Prisma

@Injectable()
export class TicketsService {
  constructor(private prisma: PrismaService) { }

  /**
   * Creates a new ticket and generates a unique, human-readable code.
   * @param createTicketDto - The DTO containing ticket data from the request.
   * @param userId - The ID of the user creating the ticket (from auth token).
   */
  async create(createTicketDto: CreateTicketDto, userId: string) {
    // --- START: Code Generation Logic ---

    return this.prisma.ticket.create({
      data: {
        ...createTicketDto,
        createdById: userId,
        status: TicketStatus.NEW,
      },
    });
  }

  findAll() {
    return this.prisma.ticket.findMany();
  }

  findOne(id: string) {
    return this.prisma.ticket.findUnique({
      where: { id }
    });
  }

  remove(id: string) {
    return this.prisma.ticket.delete({
      where: { id }
    })
  }
}
